CREATE TABLE users(
idUsers INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
nom VARCHAR(45) NOT NULL,
prenom VARCHAR(45) NOT NULL,
pseudo CHAR(20) NOT NULL,
mail VARCHAR(45) NOT NULL,
mdp VARCHAR(255) NOT NULL,
userType VARCHAR(20) NOT NULL
);

CREATE TABLE message(
idMessage INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
mail VARCHAR(70) NOT NULL,
message TEXT NOT NULL
);

CREATE TABLE categorie(
idCategorie INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
categorie VARCHAR(70) NOT NULL
);

CREATE TABLE article(
idArticle INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
titre VARCHAR(45) NOT NULL,
dateCreate DATETIME,
resume VARCHAR(45) NOT NULL,
image VARCHAR(20) NOT NULL,
description TEXT NOT NULL,
idCategorie INT(10) UNSIGNED NOT NULL,
idUsers INT(10) UNSIGNED NOT NULL
);

CREATE TABLE commentaire(
idcommentaire INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
commentaire TEXT NOT NULL,
idUsers INT(10) UNSIGNED NOT NULL,
idArticle INT(10) UNSIGNED NOT NULL
);

ALTER TABLE article ADD CONSTRAINT fk_articleCategorie_id FOREIGN KEY(idCategorie) REFERENCES categorie (idCategorie);
ALTER TABLE commentaire ADD CONSTRAINT fk_commentaireUser_id FOREIGN KEY(idUsers) REFERENCES users (idUsers);
ALTER TABLE commentaire ADD CONSTRAINT fk_commentaireArticle_id FOREIGN KEY(idArticle) REFERENCES article (idArticle);
ALTER TABLE article ADD CONSTRAINT fk_articleUsers_id FOREIGN KEY(idUsers) REFERENCES users (idUsers);

